/* Aurni, Bodhana, Mary
 * Main Menu - Window all functions are connected to
 * 6/11/23
 */
package reimagined;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;

public class MainWindow extends javax.swing.JFrame {

    //Declare all windows menu connects to
    private DecisionWindow dW;
    private UserLogin ul;
    private Achievements a;
    private OriginalStory o;
    private CreditsWindow cW;
    private Leaderboard l;

    //Assign music and default of whether it is playing
    private static Clip c = loadMusic("src/reimagined/Chopin-ballade-no-1.wav");
    private static boolean musicSwitch = false;

    //Initialize all global variables that will be accessed throughout program
    static Story cinderella = new Story("Cinderella");
    static User current = new User("");
    static ArrayList<User> userData = new ArrayList();

    public MainWindow() {
        initComponents();
        //Set up window (color, size, visual, and music)
        Color lavendar = new Color(179, 179, 230);
        getContentPane().setBackground(lavendar);
        setSize(525, 725);
        ImageIcon graphic = new ImageIcon(new ImageIcon("src/reimagined/AI-Generated Graphic Art/MainMenu.jpg").getImage().getScaledInstance(250, 250, Image.SCALE_DEFAULT));
        visual.setText("");
        visual.setIcon(graphic);
        ImageIcon musicIcon = new ImageIcon(new ImageIcon("src/reimagined/AI-Generated Graphic Art/music.png").getImage().getScaledInstance(15, 15, Image.SCALE_DEFAULT));
        musicBtn.setIcon(musicIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTitle = new javax.swing.JLabel();
        visual = new javax.swing.JLabel();
        btnUserLogin = new javax.swing.JButton();
        btnPlayAsGuest = new javax.swing.JButton();
        btnLeaderboard = new javax.swing.JButton();
        btnAchievements = new javax.swing.JButton();
        btnOgStory = new javax.swing.JButton();
        visual1 = new javax.swing.JLabel();
        musicBtn = new javax.swing.JButton();
        creditsBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTitle.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        btnTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTitle.setText("Reimagined");

        visual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        visual.setText("Visual");

        btnUserLogin.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnUserLogin.setText("User Login");
        btnUserLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserLoginActionPerformed(evt);
            }
        });

        btnPlayAsGuest.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnPlayAsGuest.setText("Play as Guest");
        btnPlayAsGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayAsGuestActionPerformed(evt);
            }
        });

        btnLeaderboard.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnLeaderboard.setText("Leaderboard");
        btnLeaderboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaderboardActionPerformed(evt);
            }
        });

        btnAchievements.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnAchievements.setText("Achievements");
        btnAchievements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAchievementsActionPerformed(evt);
            }
        });

        btnOgStory.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnOgStory.setText("Read Original Fairytale");
        btnOgStory.setToolTipText("");
        btnOgStory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOgStoryActionPerformed(evt);
            }
        });

        visual1.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        visual1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        visual1.setText("Cinderella");

        musicBtn.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        musicBtn.setText("Music");
        musicBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicBtnActionPerformed(evt);
            }
        });

        creditsBtn.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        creditsBtn.setText("Credits");
        creditsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnUserLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPlayAsGuest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLeaderboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAchievements, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnOgStory, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(visual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(btnTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(visual1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(creditsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(musicBtn)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musicBtn)
                    .addComponent(creditsBtn))
                .addGap(1, 1, 1)
                .addComponent(visual1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(visual)
                .addGap(27, 27, 27)
                .addComponent(btnUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPlayAsGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLeaderboard, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAchievements, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOgStory, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Open user login window and close main menu
     *
     * @param evt when button is clicked
     */
    private void btnUserLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserLoginActionPerformed
        if (ul == null) {
            ul = new UserLogin(this); //Create new window if it doesn't exist
        }
        ul.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnUserLoginActionPerformed
    /**
     * Open decision window and close main menu
     *
     * @param evt when button is clicked
     */
    private void btnPlayAsGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayAsGuestActionPerformed
        current = new User("");
        if (dW == null) {
            dW = new DecisionWindow(this); //Create new window if it doesn't exist
        }
        dW.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPlayAsGuestActionPerformed
    /**
     * Open leaderboard window and close main menu
     *
     * @param evt when button is clicked
     */
    private void btnLeaderboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaderboardActionPerformed
        if (l == null) {
            l = new Leaderboard(this); //Create new window if it doesn't exist
        }
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLeaderboardActionPerformed
    /**
     * Open achievements window and close main menu
     *
     * @param evt when button is clicked
     */
    private void btnAchievementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAchievementsActionPerformed
        if (a == null) {
            a = new Achievements(this); //Create new window if it doesn't exist
        }
        a.updateAchievements(); //Update achievements attribute in current user object
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAchievementsActionPerformed
    /**
     * Open original story window and close main menu
     *
     * @param evt when button is clicked
     */
    private void btnOgStoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOgStoryActionPerformed
        if (o == null) {
            o = new OriginalStory(this); //Create new window if it doesn't exist
        }
        o.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnOgStoryActionPerformed
    /**
     * Play and turn off music
     *
     * @param evt when button is clicked
     */
    private void musicBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicBtnActionPerformed
        if (musicSwitch == false) { //Start music when button is clicked
            c.start();
            c.loop(Clip.LOOP_CONTINUOUSLY); //Loop music
            musicSwitch = true; //Set switch to true, so that music is turned OFF the next time button is clicked
        } else {
            c.stop();
            musicSwitch = false; //Set switch to false, so that music is turned ON the next time button is clicked
        }
    }//GEN-LAST:event_musicBtnActionPerformed
    /**
     * Display roles of each team member and contribution to project
     *
     * @param evt when button is clicked
     */
    private void creditsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsBtnActionPerformed
        if (cW == null) {
            cW = new CreditsWindow(this); //Create new window if it doesn't exist
        }
        cW.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_creditsBtnActionPerformed

    /**
     * Loads music into Clip object
     *
     * @param location
     * @return Clip that will play when button is clicked
     */
    public static Clip loadMusic(String location) {
        try {
            File musicPath = new File(location); //Access audio file
            if (musicPath.exists()) {
                AudioInputStream audioInput = AudioSystem.getAudioInputStream(musicPath);
                c = AudioSystem.getClip(); //Generate Clip object from file
                c.open(audioInput);
            } else {
                System.out.println("The file cannot be found.");
            }
        } catch (IOException | LineUnavailableException | UnsupportedAudioFileException e) {
            System.out.println(e);
        }
        return c;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAchievements;
    private javax.swing.JButton btnLeaderboard;
    private javax.swing.JButton btnOgStory;
    private javax.swing.JButton btnPlayAsGuest;
    private javax.swing.JLabel btnTitle;
    private javax.swing.JButton btnUserLogin;
    private javax.swing.JButton creditsBtn;
    private javax.swing.JButton musicBtn;
    private javax.swing.JLabel visual;
    private javax.swing.JLabel visual1;
    // End of variables declaration//GEN-END:variables
}
