/* Aurni, Bodhana, Mary
 * User Login Window
 * 6/13/23
 */
package reimagined;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class OriginalStory extends javax.swing.JFrame {

    //Declare connecting window
    MainWindow mW;

    public OriginalStory(MainWindow m) {
        initComponents();
        //Connect to main menu
        mW = m;
        //Set up window (color and size)
        Color lavendar = new Color(179, 179, 230);
        getContentPane().setBackground(lavendar);
        setSize(525, 725);
        loadStory();
    }

    /**
     * Read original story from file and display it to user
     */
    public void loadStory() {
        String lines = ""; //Initialize an empty String to add lines to
        try {
            File f = new File("src/reimagined/Cinderella.txt");
            Scanner s = new Scanner(f);
            while (s.hasNextLine()) { //Run until there are no lines left in file and append to String
                lines += s.nextLine() + "\n";
            }
            //Update GUI by adding String to text area
            storyTxtArea.setText(lines);
            storyTxtArea.setLineWrap(true);
            //Scroll to top of text box
            storyTxtArea.setSelectionStart(0);
            storyTxtArea.setSelectionEnd(0);
        } catch (FileNotFoundException e) {
            System.out.println("Error " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        storyJScrollPane = new javax.swing.JScrollPane();
        storyTxtArea = new javax.swing.JTextArea();
        mainMenuJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("The Brothers Grimm Cinderella");

        storyTxtArea.setColumns(20);
        storyTxtArea.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        storyTxtArea.setRows(5);
        storyTxtArea.setWrapStyleWord(true);
        storyJScrollPane.setViewportView(storyTxtArea);

        mainMenuJButton.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        mainMenuJButton.setText("Back to Menu");
        mainMenuJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
            .addComponent(storyJScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainMenuJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(storyJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainMenuJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenuJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuJButtonActionPerformed
        mW.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mainMenuJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mainMenuJButton;
    private javax.swing.JScrollPane storyJScrollPane;
    private javax.swing.JTextArea storyTxtArea;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
